# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionNotice',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2048)),
                ('url', models.CharField(max_length=512)),
                ('pub_date', models.DateField()),
                ('comp_date', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='competitionnotice',
            name='comp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Type'),
        ),
        migrations.AddField(
            model_name='competitionnotice',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Publisher'),
        ),
    ]
